# Generated by Django 4.0.1 on 2022-07-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
